###########
# BUILDER #
###########

# image base
FROM node:11.12.0-alpine as builder

# estableciendo directorio de trabajo
WORKDIR /usr/src/app

# instalando dependencias de la app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci
RUN npm install react-scripts@2.1.8 -g --silent

# estableciendo variables de entorno
ARG REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

# creando compilación
COPY . /usr/src/app
RUN npm run build


#########
# FINAL #
#########

# imagen base
FROM nginx:1.15.9-alpine

# copiando archivos estáticos
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# exponiendo puerto
EXPOSE 80

# ejecutando nginx
CMD ["nginx", "-g", "daemon off;"]
